### ISSUE TITLE
Merge sparql-router-ui and move the API activity to /api/ path

### ISSUE THREAD

**Issue by ColinMaudry** [ColinMaudry/sparql-router#45]
I first wanted to develop the API engine and the UI that uses it as separate projects. However:
- I think many people will always want both, not just the API engine
- For those who want both, it's a pain to set up two URLs (subdomain, virtual server, reverse proxies, etc.) where one could do fine.
- When deployed as a whole, the UI part has hardly any CPU/memory footprint if not used. So if someone doesn't use it, well it doesn't bother them either.

I'll use the method described here to achieve this merge: http://jasonkarns.com/blog/merge-two-git-repositories-into-one/ by @jasonkarns.

**Comment by ColinMaudry** [comment]
Finally, I won't import the commit history of UI, I will just add the files. Not worth the effort.

**Comment by jasonkarns** [comment]
I just wanted to share that git has added a sub command git-subtree that
makes this type of repo merge trivial (a single command). My blog post is
now obsolete for the common case. (There are still other use cases for the
subtree merge.)

git subtree add --prefix <subdir path> <repo url>
On May 15, 2016 9:43 AM, "Colin Maudry" notifications@github.com wrote:

Closed #45 https://github.com/ColinMaudry/sparql-router/issues/45.

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
https://github.com/ColinMaudry/sparql-router/issues/45#event-660970561

**Comment by ColinMaudry** [comment]
Too late for this one, I just copied the files over. Its was only 20 commits or so. But thanks!
